<?php
/**
 * @file
 * Code for the !&# Analytics module.
 */

/**
 * Implements hook_admin_paths().
 */
function bangpoundanalytics_admin_paths() {
  $paths = array(
    'node/*/metrics' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_menu().
 */
function bangpoundanalytics_menu() {
  $items['node/%node/metrics'] = array(
    'title' => 'Metrics',
    'page callback' => 'bangpoundanalytics_page',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'bangpoundanalytics.pages.inc',
  );
  return $items;
}

function bangpoundanalytics_theme() {
  return array(
    'analytics' => array(
      'variables' => array('client_id' => NULL, 'ids' => NULL, 'path' => NULL),
      'template' => 'analytics',
    ),
  );
}
